import { Course } from "@/src/types/courses/courses";

export const courses: Course[] = [
  {
    id: 1,
    title: "دورة Vue JavaScript الشاملة",
    desc: "وصف الكورس وصف الكورس وصف الكورس وصف الكورس",
    duration: "10 ساعات",
    originalPrice: 92.9,
    discountedPrice: 24.92,
    discountPercentage: "20% خصم",
    badge: "الأكثر مبيعاً",
    imageUrl: "/imgs/course-1.png",
    platform: "by Kitani Studio",
    instructor: "أحمد محمد",
    lectures: 25,
    students: 1200,
    language: "العربية",
    isEnrolled: false,
    rating: 4,
    sections: [
      { id: "s1", title: "المقدمة", duration: "30 دقيقة", lectures: 3 },
      { id: "s2", title: "الأساسيات", duration: "2 ساعة", lectures: 8 },
      { id: "s3", title: "المشاريع العملية", duration: "7 ساعة", lectures: 14 },
    ],
  },
  {
    id: 2,
    title: "تعلم البرمجة في 30 يوماً",
    desc: "وصف الكورس وصف الكورس وصف الكورس وصف الكورس",
    duration: "30 ساعة",
    originalPrice: 92.9,
    discountedPrice: 24.92,
    discountPercentage: "20% خصم",
    imageUrl: "/imgs/course-2.png",
    instructor: "سارة أحمد",
    lectures: 30,
    students: 900,
    rating: 5,
    language: "العربية",
    isEnrolled: true,
    sections: [
      { id: "s1", title: "اليوم 1-5", duration: "5 ساعات", lectures: 5 },
      { id: "s2", title: "اليوم 6-15", duration: "10 ساعات", lectures: 10 },
      { id: "s3", title: "اليوم 16-30", duration: "15 ساعات", lectures: 15 },
    ],
  },
  {
    id: 3,
    title: "اصنع تطبيق أوبر كامل",
    desc: "وصف الكورس وصف الكورس وصف الكورس وصف الكورس",
    duration: "12 ساعة",
    originalPrice: 120.0,
    discountedPrice: 35.0,
    discountPercentage: "25% خصم",
    imageUrl: "/imgs/course-3.png",
    platform: "Uber Clone",
    instructor: "محمد علي",
    lectures: 20,
    students: 1500,
    rating: 3,
    language: "العربية",
    isEnrolled: false,
    sections: [
      { id: "s1", title: "تصميم الواجهة", duration: "4 ساعة", lectures: 5 },
      {
        id: "s2",
        title: "إعداد قاعدة البيانات",
        duration: "3 ساعة",
        lectures: 5,
      },
      { id: "s3", title: "البرمجة الخلفية", duration: "5 ساعة", lectures: 10 },
    ],
  },
  {
    id: 4,
    title: "تعلم React JS خطوة بخطوة",
    desc: "وصف الكورس وصف الكورس وصف الكورس وصف الكورس",
    duration: "15 ساعة",
    originalPrice: 100.0,
    discountedPrice: 30.0,
    discountPercentage: "30% خصم",
    imageUrl: "/imgs/course-4.png",
    instructor: "ليلى سمير",
    lectures: 28,
    students: 800,
    rating: 4,
    language: "العربية",
    isEnrolled: true,
    sections: [
      { id: "s1", title: "مقدمة", duration: "1 ساعة", lectures: 2 },
      {
        id: "s2",
        title: "المكونات الأساسية",
        duration: "5 ساعات",
        lectures: 10,
      },
      {
        id: "s3",
        title: "المشاريع العملية",
        duration: "9 ساعات",
        lectures: 16,
      },
    ],
  },
];

export const singleCourse = {
  id: 1,
  title: "دورة Vue JavaScript الشاملة",
  desc: "وصف الكورس وصف الكورس وصف الكورس وصف الكورس",
  duration: "10 ساعات",
  originalPrice: 92.9,
  discountedPrice: 24.92,
  discountPercentage: "20% خصم",
  badge: "الأكثر مبيعاً",
  imageUrl: "/imgs/course-1.png",
  platform: "by Kitani Studio",
  instructor: "أحمد محمد",
  lectures: 25,
  students: 1200,
  rating: 4,

  language: "العربية",
  isEnrolled: true,
  sections: [
    { id: "s1", title: "المقدمة", duration: "30 دقيقة", lectures: 3 },
    { id: "s2", title: "الأساسيات", duration: "2 ساعة", lectures: 8 },
    { id: "s3", title: "المشاريع العملية", duration: "7 ساعة", lectures: 14 },
  ],
};
export const singleCertificate = {
    studentName: 'Name',
    courseName: 'UX/UI Design Principles',
    completionDate: '12-10-2024',
    // You can replace this with your actual certificate image URL
    certificateImage: '/imgs/certificate.jpg'
  }